-- Reservations, pickup orders, callback requests, and non-personal call metrics.
-- migrate:up
CREATE TABLE reservations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),restaurant_id uuid NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,table_id uuid NOT NULL REFERENCES restaurant_tables(id) ON DELETE RESTRICT,guest_name text NOT NULL CHECK(btrim(guest_name)<>''),guest_phone text,party_size int NOT NULL CHECK(party_size BETWEEN 1 AND 100),starts_at timestamptz NOT NULL,ends_at timestamptz NOT NULL,status text NOT NULL DEFAULT 'confirmed' CHECK(status IN('confirmed','cancelled','no_show','seated')),source text NOT NULL CHECK(source IN('phone','portal','test')),language char(2) NOT NULL CHECK(language IN('de','ru','en')),notes text,created_at timestamptz NOT NULL DEFAULT now(),delete_after date,CHECK(ends_at>starts_at),CONSTRAINT reservations_no_overlap EXCLUDE USING gist(table_id WITH =,tstzrange(starts_at,ends_at) WITH &&) WHERE(status IN('confirmed','seated')));
CREATE INDEX reservations_by_date_idx ON reservations(restaurant_id,starts_at); CREATE INDEX reservations_by_phone_idx ON reservations(restaurant_id,guest_phone); CREATE INDEX reservations_purge_idx ON reservations(delete_after) WHERE delete_after IS NOT NULL;
CREATE TABLE pickup_orders(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),restaurant_id uuid NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,order_number text NOT NULL CHECK(order_number~'^[0-9]{4}$'),guest_name text NOT NULL CHECK(btrim(guest_name)<>''),guest_phone text,ready_at timestamptz NOT NULL,total_cents int NOT NULL CHECK(total_cents>=0),status text NOT NULL DEFAULT 'new' CHECK(status IN('new','confirmed','preparing','ready','picked_up','cancelled')),source text NOT NULL CHECK(source IN('phone','portal','test')),language char(2) NOT NULL CHECK(language IN('de','ru','en')),notes text,created_at timestamptz NOT NULL DEFAULT now(),delete_after date);
CREATE UNIQUE INDEX pickup_orders_active_number_uk ON pickup_orders(restaurant_id,order_number) WHERE status IN('new','confirmed','preparing','ready'); CREATE INDEX pickup_orders_by_ready_idx ON pickup_orders(restaurant_id,ready_at); CREATE INDEX pickup_orders_purge_idx ON pickup_orders(delete_after) WHERE delete_after IS NOT NULL;
CREATE TABLE pickup_order_items(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),order_id uuid NOT NULL REFERENCES pickup_orders(id) ON DELETE CASCADE,menu_item_id uuid NOT NULL REFERENCES menu_items(id) ON DELETE RESTRICT,quantity int NOT NULL CHECK(quantity BETWEEN 1 AND 50),unit_price_cents int NOT NULL CHECK(unit_price_cents>=0),note text); CREATE INDEX pickup_order_items_order_idx ON pickup_order_items(order_id);
CREATE TABLE callback_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),restaurant_id uuid NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,caller_phone text,language char(2) NOT NULL CHECK(language IN('de','ru','en')),summary text NOT NULL CHECK(btrim(summary)<>'' AND length(summary)<=400),category text NOT NULL CHECK(category IN('banquet','complaint','special','other')),status text NOT NULL DEFAULT 'new' CHECK(status IN('new','in_progress','done')),created_at timestamptz NOT NULL DEFAULT now(),handled_by text,handled_at timestamptz,delete_after date); CREATE INDEX callback_requests_queue_idx ON callback_requests(restaurant_id,status,created_at DESC); CREATE INDEX callback_requests_purge_idx ON callback_requests(delete_after) WHERE delete_after IS NOT NULL;
CREATE TABLE call_logs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),restaurant_id uuid NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,room_name text NOT NULL,started_at timestamptz NOT NULL DEFAULT now(),ended_at timestamptz,language char(2) CHECK(language IS NULL OR language IN('de','ru','en')),outcome text CHECK(outcome IS NULL OR outcome IN('reservation','pickup','info','callback','failed')),turn_count int NOT NULL DEFAULT 0 CHECK(turn_count>=0),is_test bool NOT NULL DEFAULT false,reservation_id uuid REFERENCES reservations(id) ON DELETE SET NULL,order_id uuid REFERENCES pickup_orders(id) ON DELETE SET NULL,callback_id uuid REFERENCES callback_requests(id) ON DELETE SET NULL); CREATE INDEX call_logs_by_date_idx ON call_logs(restaurant_id,started_at DESC);
-- migrate:down
DROP TABLE call_logs; DROP TABLE callback_requests; DROP TABLE pickup_order_items; DROP TABLE pickup_orders; DROP TABLE reservations;
